version: '{build}'
os: Visual Studio 2015

platform: x64

environment:
  PYTHON3: "C:\\Python36"
  
init:
  - cmd: set PATH=%PYTHON3%;%PYTHON3%\scripts;%PATH%

install:
  - pip install meson ninja
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - msbuild gstreamer-sharp.sln /t:Build /p:Configuration=Release /p:TargetFramework=v4.0
  - meson build/

build: off

cache:
  - C:\Gstreamer\1.0\x86_64\
